services:
  - type: web
    name: davson-portfolio-api
    runtime: node
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js

  - type: web
    name: davson-portfolio
    runtime: static
    buildCommand: mkdir -p dist && cp -r index.html css js images dist/
    staticPublishPath: dist
